### ISSUE TITLE
Add functionality.

### ISSUE THREAD

**Issue by Knopaleo** [oziavci/cat-dog-feeder-wifi#2]

**Comment by durulorhan** [comment]
rica etsen acilen kabloların nasıl bağlandığını gösterir misiniz

**Comment by oziavci** [comment]
Selam, bağlantılar bu şekilde. Şema yok fakat internette bulabileceğin bağlantılarla aynı, sadece güç kablosuna yapılan ek bir parça ile gücü çoklayarak motoru da besledim.

![IMG_50033](https://github.com/user-attachments/assets/3c30f4dd-6aa7-4863-8927-147a1d95bf30)
![IMG_5002](https://github.com/user-attachments/assets/6472935b-cf53-4f00-9047-965c63188281)
![IMG_5004](https://github.com/user-attachments/assets/8a4d66f4-00e9-44b6-989d-23134e83f155)
![IMG_5001-2](https://github.com/user-attachments/assets/ab09cee8-371c-4c54-bb35-a8d1e594b9c1)
![c98eba6d-460b-45ce-b867-56f0eb7900a8](https://github.com/user-attachments/assets/1834ab8d-fdd2-42a8-be27-0344907ba93e)

Umarım başarırsın, kolay gelsin
